using DTC.Api.Dtos.Braket;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class BraketMapper
    {
        // Entity -> DTO
        public static BraketDto ToBraketDto(this Braket braket)
        {
            return new BraketDto
            {
                Id = braket.Id,
                TournamentId = braket.TournamentId,
                Sequence = braket.Sequence,
                Name = braket.Name,
                PlannedStart = braket.PlannedStart,
                PlannedEnd = braket.PlannedEnd,
                Status = braket.Status,
                Phase = braket.Phase,
            };
        }


        // Create DTO -> Entity
        public static Braket ToEntityFromCreate(this CreateBraketDto dto)
        {
            return new Braket
            {
                // Id is auto-generated by the database
                TournamentId = dto.TournamentId,
                Sequence = dto.Sequence,
                Name = dto.Name?.Trim(),
                PlannedStart = dto.PlannedStart,
                PlannedEnd = dto.PlannedEnd,
                Status = dto.Status,
                Phase = dto.Phase
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateBraketEntity(
            this UpdateBraketDto dto,
            Braket braket)
        {
            braket.TournamentId = dto.TournamentId;
            braket.Sequence = dto.Sequence;
            braket.Name = dto.Name?.Trim();
            braket.PlannedStart = dto.PlannedStart;
            braket.PlannedEnd = dto.PlannedEnd;
            braket.Status = dto.Status;
            braket.Phase = dto.Phase;
        }
    }
}
