using DTC.Api.Dtos.Braket;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class BraketMapper
    {
        // Entity -> DTO
        public static BraketDto ToBraketDto(this Braket round)
        {
            return new BraketDto
            {
                Id = round.Id,
                TournamentId = round.TournamentId,
                Sequence = round.Sequence,
                Name = round.Name,
                PlannedStart = round.PlannedStart,
                PlannedEnd = round.PlannedEnd,
                Status = round.Status,
                Phase = round.Phase,
            };
        }


        // Create DTO -> Entity
        public static Braket ToEntityFromCreate(this CreateBraketDto dto)
        {
            return new Braket
            {
                // Id is auto-generated by the database
                TournamentId = dto.TournamentId,
                Sequence = dto.Sequence,
                Name = dto.Name?.Trim(),
                PlannedStart = dto.PlannedStart,
                PlannedEnd = dto.PlannedEnd,
                Status = dto.Status,
                Phase = dto.Phase
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateBraketEntity(
            this UpdateBraketDto dto,
            Braket round)
        {
            round.TournamentId = dto.TournamentId;
            round.Sequence = dto.Sequence;
            round.Name = dto.Name?.Trim();
            round.PlannedStart = dto.PlannedStart;
            round.PlannedEnd = dto.PlannedEnd;
            round.Status = dto.Status;
            round.Phase = dto.Phase;
        }
    }
}
