using DTC.Api.Dtos.Group;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class GroupMapper
    {
        // Entity -> DTO
        public static GroupDto ToGroupDto(this Group group)
        {
            return new GroupDto
            {
                Id = group.Id,
                TournamentId = group.TournamentId,
                Sequence = group.Sequence,
                Name = group.Name,
                QualifiersCount = group.QualifiersCount,
            };
        }


        // Create DTO -> Entity
        public static Group ToEntityFromCreate(this CreateGroupDto dto)
        {
            return new Group
            {
                // Id is auto-generated by the database
                TournamentId = dto.TournamentId,
                Sequence = dto.Sequence,
                Name = dto.Name.Trim(),
                QualifiersCount = dto.QualifiersCount
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateGroupEntity(
            this UpdateGroupDto dto,
            Group group)
        {
            group.TournamentId = dto.TournamentId;
            group.Sequence = dto.Sequence;
            group.Name = dto.Name.Trim();
            group.QualifiersCount = dto.QualifiersCount;
        }
    }
}
