using DTC.Api.Dtos.GroupPlayer;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class GroupPlayerMapper
    {
        // Entity -> DTO
        public static GroupPlayerDto ToGroupPlayerDto(
            this GroupPlayer groupPlayer)
        {
            return new GroupPlayerDto
            {
                Id = groupPlayer.Id,
                GroupId = groupPlayer.GroupId,
                TournamentPlayerId = groupPlayer.TournamentPlayer?.Id ?? -1
            };
        }


        // Create DTO -> Entity
        public static GroupPlayer ToEntityFromCreate(
            this CreateGroupPlayerDto dto)
        {
            return new GroupPlayer
            {
                // Id is auto-generated by the database
                GroupId = dto.GroupId,
                TournamentPlayerId = dto.TournamentPlayerId
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateGroupPlayerEntity(
            this UpdateGroupPlayerDto dto,
            GroupPlayer groupPlayer)
        {
            groupPlayer.GroupId = dto.GroupId;
            groupPlayer.TournamentPlayerId = dto.TournamentPlayerId;
        }
    }
}
