using DTC.Api.Dtos.Location;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class LocationMapper
    {
        // Entity -> DTO
        public static LocationDto ToLocationDto(this Location location)
        {
            return new LocationDto
            {
                Id = location.Id,
                Name = location.Name,
                Address = location.Address
            };
        }


        // Create DTO -> Entity
        public static Location ToEntityFromCreate(this CreateLocationDto dto)
        {
            return new Location
            {
                // Id is auto-generated by the database
                Name = dto.Name.Trim(),
                Address = dto.Address?.Trim()
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateLocationEntity(
            this UpdateLocationDto dto,
            Location location)
        {
            location.Name = dto.Name.Trim();
            location.Address = dto.Address?.Trim();
        }
    }
}
