using DTC.Api.Dtos.MatchParticipant;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class MatchParticipantMapper
    {
        // Entity -> DTO
        public static MatchParticipantDto ToMatchParticipantDto(
            this MatchParticipant matchParticipant)
        {
            return new MatchParticipantDto
            {
                Id = matchParticipant.Id,
                MatchId = matchParticipant.MatchId,
                TournamentPlayerId = matchParticipant.TournamentPlayer?.Id ?? -1,
                Score = matchParticipant.Score,
                IsWinner = matchParticipant.IsWinner
            };
        }


        // Create DTO -> Entity
        public static MatchParticipant ToEntityFromCreate(
            this CreateMatchParticipantDto dto)
        {
            return new MatchParticipant
            {
                // Id is auto-generated by the database
                MatchId = dto.MatchId,
                TournamentPlayerId = dto.TournamentPlayerId,
                Score = dto.Score,
                IsWinner = dto.IsWinner
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateMatchParticipantEntity(
            this UpdateMatchParticipantDto dto,
            MatchParticipant matchParticipant)
        {
            matchParticipant.MatchId = dto.MatchId;
            matchParticipant.TournamentPlayerId = dto.TournamentPlayerId;
            matchParticipant.Score = dto.Score;
            matchParticipant.IsWinner = dto.IsWinner;
        }
    }
}
