using DTC.Api.Dtos.Player;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class PlayerMapper
    {
        public static PlayerDto ToPlayerDto(this Player player)
        {
            return new PlayerDto
            {
                Id = player.Id,
                FirstName = player.FirstName,
                LastName = player.LastName,
                Nickname = player.Nickname
            };
        }

        // Create DTO -> Entity
        public static Player ToEntityFromCreate(this CreatePlayerDto dto)
        {
            return new Player
            {
                // Id is auto-generated by the database
                FirstName = dto.FirstName.Trim(),
                LastName = dto.LastName.Trim(),
                Nickname = dto.Nickname?.Trim()
            };
        }

        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdatePlayerModel(this UpdatePlayerDto dto, Player player)
        {
            player.FirstName = dto.FirstName.Trim();
            player.LastName = dto.LastName.Trim();
            player.Nickname = dto.Nickname?.Trim();
        }
    }
}
