using DTC.Api.Dtos.TournamentPlayer;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class TournamentPlayerMapper
    {
        // Entity -> DTO
        public static TournamentPlayerDto ToTournamentPlayerDto(
            this TournamentPlayer tournamentPlayer)
        {
            return new TournamentPlayerDto
            {
                Id = tournamentPlayer.Id,
                TournamentId = tournamentPlayer.TournamentId,
                IsQualified = tournamentPlayer.IsQualified,
                PlayerId = tournamentPlayer.PlayerId,
                Player =  tournamentPlayer.Player? .ToPlayerDto() ?? null,
            };
        }


        // Create DTO -> Entity
        public static TournamentPlayer ToEntityFromCreate(
            this CreateTournamentPlayerDto dto)
        {
            return new TournamentPlayer
            {
                // Id is auto-generated by the database
                TournamentId = dto.TournamentId,
                PlayerId = dto.PlayerId,
                IsQualified = dto.IsQualified,
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateTournamentPlayerEntity(
            this UpdateTournamentPlayerDto dto,
            TournamentPlayer tournamentPlayer)
        {
            tournamentPlayer.TournamentId = dto.TournamentId;
            tournamentPlayer.PlayerId = dto.PlayerId;
            tournamentPlayer.IsQualified = dto.IsQualified;
        }
    }
}
