using DTC.Api.Dtos.Tournament;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class TournamentMapper
    {
        // Entity -> DTO
        public static TournamentDto ToTournamentDto(
            this Tournament tournament)
        {
            return new TournamentDto
            {
                Id = tournament.Id,
                Name = tournament.Name,
                StartDate = tournament.StartDate,
                Description = tournament.Description,
                Mode = tournament.Mode,
                Status = tournament.Status,
                MatchDurationMinutes = tournament.MatchDurationMinutes,
                BreakBetweenMatchesMinutes = tournament.BreakBetweenMatchesMinutes,
                TournamentPlayers = tournament.TournamentPlayers?.Select(p => p.ToTournamentPlayerDto()).ToList() ?? [],
                Rounds = tournament.Rounds?.Select(r => r.ToRoundDto()).ToList() ?? [],
                Groups = tournament.Groups?.Select(g => g.ToGroupDto()).ToList() ?? []

            };
        }


        // Create DTO -> Entity
        public static Tournament ToEntityFromCreate(
            this CreateTournamentDto dto)
        {
            return new Tournament
            {
                // Id is auto-generated by the database
                Name = dto.Name.Trim(),
                StartDate = dto.StartDate,
                Description = dto.Description?.Trim(),
                Mode = dto.Mode,
                Status = dto.Status,
                MatchDurationMinutes = dto.MatchDurationMinutes,
                BreakBetweenMatchesMinutes = dto.BreakBetweenMatchesMinutes
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateTournamentEntity(
            this UpdateTournamentDto dto,
            Tournament tournament)
        {
            tournament.Name = dto.Name.Trim();
            tournament.StartDate = dto.StartDate;
            tournament.Description = dto.Description?.Trim();
            tournament.Mode = dto.Mode;
            tournament.Status = dto.Status;
            tournament.MatchDurationMinutes = dto.MatchDurationMinutes;
            tournament.BreakBetweenMatchesMinutes = dto.BreakBetweenMatchesMinutes;
        }
    }
}
