using DTC.Api.Dtos.TournamentPlayer;
using DTC.Api.Models;

namespace DTC.Api.Mappers
{
    public static class TournamentPlayerMapper
    {
        // Entity -> DTO
        public static TournamentPlayerDto ToTournamentPlayerDto(
            this TournamentPlayer tournamentPlayer)
        {
            return new TournamentPlayerDto
            {
                Id = tournamentPlayer.Id,
                TournamentId = tournamentPlayer.TournamentId,
                PlayerId = tournamentPlayer.PlayerId
            };
        }


        // Create DTO -> Entity
        public static TournamentPlayer ToEntityFromCreate(
            this CreateTournamentPlayerDto dto)
        {
            return new TournamentPlayer
            {
                // Id is auto-generated by the database
                TournamentId = dto.TournamentId,
                PlayerId = dto.PlayerId
            };
        }


        // Update DTO -> vorhandene Entity aktualisieren
        public static void UpdateTournamentPlayerEntity(
            this UpdateTournamentPlayerDto dto,
            TournamentPlayer tournamentPlayer)
        {
            tournamentPlayer.TournamentId = dto.TournamentId;
            tournamentPlayer.PlayerId = dto.PlayerId;
        }
    }
}
